<div class="image">

  <img style="float: right;" src="https://dx5i3n065oxey.cloudfront.net/platform/4186/assets/logo.png?v=2e76f927-9482-4bfb-9092-d9a0b595cd2c" width="45%" align="right">
      <h4>
          <p style="font-size:20pt">Programming for Business Analytics</p>
          <p style="font-size:15pt">Q6 Practice 3</p>
      </h4>
</div>

- Make sure you have executed the code in the cell below.
- Make sure you read the questions carefully and follow the instructions.
- Make sure you put the answers in the Answer cells.
- Please do not put your answers in comments (after #).
- Please do not add any new cells between the Question and Answer cells.
- Please do not change the names of the variables in Answer cells.
- Please do not assign the expected result directly to the variable.
- Please do not change the pre-defined variables.

<div class="alert alert-warning">
<b>QUESTION 1: </b> 
<p>Write code to create a $6\times6$ array with row values being integers ranging from 2 to 7. Assign the result to variable <code>arr_1</code>. Print <code>arr_1</code>, the expected output is shown below.</p>
    
```
[[2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]]
```
</div>

In [7]:
###ANSWER(1). 
# Write your code here.
import numpy as np
arr_1 = np.ones(36).reshape(6,6) * np.arange(8)[2:]
print(arr_1)

[[2. 3. 4. 5. 6. 7.]
 [2. 3. 4. 5. 6. 7.]
 [2. 3. 4. 5. 6. 7.]
 [2. 3. 4. 5. 6. 7.]
 [2. 3. 4. 5. 6. 7.]
 [2. 3. 4. 5. 6. 7.]]


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 2:</b>
<p>An array has been defined in the cell below.</p>

```python
arr_3by5 = np.array([[4, 2, 3, 1, 3],
                     [1, 1, 3, 1, 3],
                     [0, 4, 4, 2, 2]])
```

<p>Write code to transpose <code>arr_3by5</code> and assign the result to <code>arr_5by3</code>. Print <code>arr_5by3</code>, the expected output is shown below.</p>
    

```
[[4 1 0]
 [2 1 4]
 [3 3 4]
 [1 1 2]
 [3 3 2]]
```
</div>

In [14]:
###ANSWER(2).
arr_3by5 = np.array([[4, 2, 3, 1, 3],
                     [1, 1, 3, 1, 3],
                     [0, 4, 4, 2, 2]])
# Write your code here.
arr_5by3 = arr_3by5.T
arr_5by3

array([[4, 1, 0],
       [2, 1, 4],
       [3, 3, 4],
       [1, 1, 2],
       [3, 3, 2]])

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 3:</b>
<p>Use <code>eye</code> and <code>ones</code> functions to create a $5\times5$ array called <code>arr_3</code>. The expected output when printing <code>arr_3</code> is shown below.</p>
    
```
[[1 2 2 2 1]
 [2 1 2 1 2]
 [2 2 0 2 2]
 [2 1 2 1 2]
 [1 2 2 2 1]]  
```
</div>

In [27]:
###ANSWER(3)
# Write your code here.
arr_3 = np.ones((5,5)) +1 - np.eye(5)- np.eye(5)[::-1]
arr_3

array([[1., 2., 2., 2., 1.],
       [2., 1., 2., 1., 2.],
       [2., 2., 0., 2., 2.],
       [2., 1., 2., 1., 2.],
       [1., 2., 2., 2., 1.]])

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 4: </b> 
<p> An array <code>arr_4</code> has been defined.</p>
    
```python
arr_4 = np.array([1, 2, 1, 1, 30, 4, 3, 11, 1, 2, 1, 1, 2, 1, 6, 10, 7, 1, 9, 1, 1, 1])
```
<p>Write <b>ONE LINE</b> of code to find the index of the <b>6th</b> number <b>1</b> in <code>arr_4</code>. Assign the result to variable <code>index_6</code>. Print <code>index_6</code>, the expected output is <code>11</code>.</p>
    

</div>

In [52]:
###ANSWER(4). 
arr_4 = np.array([1, 2, 1, 1, 30, 4, 3, 11, 1, 2, 1, 1, 2, 1, 6, 10, 7, 1, 9, 1, 1, 1])
index_6 =  np.where(arr_4 == 1)[0][5]# Write your code here.
d = 0
for i in list(arr_4):
    if i == 1:
        d += 1
        if d == 6:
            break
            print(list(arr_4).index(i))


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 5: </b> 
<p> Create an $8\times8$ array called <code>checkerboard</code> with the checkerboard pattern. Print <code>checkerboard</code>, the expected output is shown below.</p>
    
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

</div>

In [69]:
###ANSWER(5). 
# Write your code here.
checkerboard = np.ones(64).reshape(8,8)
checkerboard[::2,::2] = 0
checkerboard[1::2,1::2] = 0
#checkerboad = checkerboard.reshape((9,8))
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning"> 
<b>QUESTION 6:</b> 
<p>An array <code>arr_6</code> has been defined.</p>
    
```python
arr_6 = np.array([38.2, 35.1, np.nan, 29.5, 25.6, np.nan, np.nan, 19.2, 32.4, np.nan, 29.5, np.nan])
```

<p>Reshape the array into $3\times4$ and fill in the missing values with 15. Print <code>arr_6</code>, the expected output is shown below.</p>

```
[[38.2 35.1 15.  29.5]
 [25.6 15.  15.  19.2]
 [32.4 15.  29.5 15. ]]
```    
</div>

In [79]:
###ANSWER(6)
arr_6 = np.array([38.2, 35.1, np.nan, 29.5, 25.6, np.nan, np.nan, 19.2, 32.4, np.nan, 29.5, np.nan])
# Write your code here
arr_6 = arr_6.reshape((3,4))
arr_6[np.isnan(arr_6)] = 15
print(arr_6)

[[38.2 35.1 15.  29.5]
 [25.6 15.  15.  19.2]
 [32.4 15.  29.5 15. ]]


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 7:</b> 

<p>Write <b>ONE LINE</b> of code to create a $5\times5$ matrix with values 1,2,3,4 below the diagonal called <code>arr_7</code>. The expected output when printing <code>arr_7</code> is shown below.</p>
    
```
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
```

</div>

In [ ]:
###ANSWER(7). 
arr_7 = # Write your code here.

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 8: </b> 
<p> An array <code>array_4d</code> has been defined.</p>
    
```python
array_4d = np.array([[[[1, 84, 3], [8, 0, 47]], [[7, 9, 25], [68, 72, 46]]],
                    [[[9, 7, 6], [4, 9, 87]], [[2, 3, 3], [77, 4, 21]]],
                    [[[3, 80, 26], [52, 71, 64]],[[0, 0, 2], [67, 92, 58]]],
                    [[[2, 10, 3], [7, 55, 96]], [[105, 1, 7],[174, 8, 49]]]])
```
<p>Write code to convert <code>array_4d</code> into a flat <b>1d array</b>. Assign the result to the variable <code>array_1d</code>. Print <code>array_1d</code>, the expected output is shown below.</p>
     
```
[  1  84   3   8   0  47   7   9  25  68  72  46   9   7   6   4   9  87
   2   3   3  77   4  21   3  80  26  52  71  64   0   0   2  67  92  58
   2  10   3   7  55  96 105   1   7 174   8  49]
```   
</div>

In [86]:
###ANSWER(8). 
array_4d = np.array([[[[1, 84, 3], [8, 0, 47]], [[7, 9, 25], [68, 72, 46]]],
                    [[[9, 7, 6], [4, 9, 87]], [[2, 3, 3], [77, 4, 21]]],
                    [[[3, 80, 26], [52, 71, 64]],[[0, 0, 2], [67, 92, 58]]],
                    [[[2, 10, 3], [7, 55, 96]], [[105, 1, 7],[174, 8, 49]]]])

# Write your code here.
array_1d = array_4d.reshape(np.product(array_4d.shape))
print(array_1d)

[  1  84   3   8   0  47   7   9  25  68  72  46   9   7   6   4   9  87
   2   3   3  77   4  21   3  80  26  52  71  64   0   0   2  67  92  58
   2  10   3   7  55  96 105   1   7 174   8  49]


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning"> 
<b>QUESTION 9:</b> 

<p>Use <code>identity</code> function to create a $5\times5$ array called <code>arr_9</code>. The expected output when printing <code>arr_9</code> is shown below.</p>

```
[[1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 2. 0. 0.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]
```

</div>

In [95]:
###ANSWEnp.entitR(9).
arr_9 = np.identity(5).reshape((5,5))
arr_9 = arr_9 + arr_9[::-1]
# Write your code here
print(arr_9)

[[1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 2. 0. 0.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 10: </b> 
<p> An array <code>arr_10</code> has been defined.</p>
    
```python
arr_10 = np.array([[ 1,  9,  4,  8,  8,  1,  5,  3,  6,  10],
                   [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  8],
                   [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
                   [ 8,  8,  1,  3,  5, 10,  4,  3,  6,  9],
                   [ 10,  1,  8,  7,  3,  1,  7,  3,  6,  2],
                   [ 9,  2,  6,  4,  3,  9,  4,  6,  1, 10]])
```
<p>Write code to generate a new array called <code>count_rowwise</code> where values in each row of the array are the counts of occurances of integers ranging from 1 to 10 for the corresponding row in <code>arr_10</code>. Print <code>count_rowwise</code>, the expected output is shown below.</p>
    
```
[[2 0 1 1 1 1 0 2 1 1]
 [2 1 2 0 1 0 1 1 1 1]
 [0 3 0 2 3 1 0 1 0 0]
 [1 0 2 1 1 1 0 2 1 1]
 [2 1 2 0 0 1 2 1 0 1]
 [1 1 1 2 0 2 0 0 2 1]]
```

</div>

In [ ]:
###ANSWER(10). 
arr_10 = np.array([[ 1,  9,  4,  8,  8,  1,  5,  3,  6,  10],
                   [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  8],
                   [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
                   [ 8,  8,  1,  3,  5, 10,  4,  3,  6,  9],
                   [ 10,  1,  8,  7,  3,  1,  7,  3,  6,  2],
                   [ 9,  2,  6,  4,  3,  9,  4,  6,  1, 10]])

count_rowwise =  # Write your code here

In [ ]:
#Please leave this cell blank.