<div class="image">

  <img style="float: right;" src="https://dx5i3n065oxey.cloudfront.net/platform/4186/assets/logo.png?v=2e76f927-9482-4bfb-9092-d9a0b595cd2c" width="45%" align="right">
      <h4>
          <p style="font-size:20pt">Programming for Business Analytics</p>
          <p style="font-size:15pt">Q6 Practice 2</p>
      </h4>
</div>

- Make sure you have executed the code in the cell below.
- Make sure you read the questions carefully and follow the instructions.
- Make sure you put the answers in the Answer cells.
- Please do not put your answers in comments (after #).
- Please do not add any new cells between the Question and Answer cells.
- Please do not change the names of the variables in Answer cells.
- Please do not assign the expected result directly to the variable.
- Please do not change the pre-defined variables.

In [ ]:
#Please import numpy and make sure your Jupyter Notebook environment is running a Python 3 kernel 
import numpy as np
import IPython
assert IPython.version_info[0] >= 3, "Your version of IPython is too old, please update it."
%autosave 120

<div class="alert alert-warning">
<b>QUESTION 1:</b>
<p>Using <b>ONE LINE</b> of code, create an array called <code>arr_1</code>. If you print <code>arr_1</code>, the expected output is shown as below.</p>
    
```
[[1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1]]
```

</div>

In [ ]:
###ANSWER(1)
arr_1 = np.eye(4).reshape(2,8).astype(int) # Write your code in one line
print(arr_1)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 2:</b>
<p>An array has been defined in the cell below.</p>
    
```python
arr_2 = np.array([2, 3, 4, 1, 8, 1, 7, 2, 4, 3, 6, 5, 7, 0, 5, 7, 9, 3, 2, 4]).reshape(4, 5)    
```

<p>For the elements in each column, subtract the second smallest value of the corresponding column and assign the result to the variable <code>arr_2</code>. If you print <code>arr_2</code>, the expected output is shown as below.</p>
    
```
[[ 0 -2  1  0  4]
 [-1  2 -1  3 -1]
 [ 4  0  4 -1  1]
 [ 5  4  0  1  0]]
```

</div>

In [2]:
###ANSWER(2)
import numpy as np
arr_2 = np.array([2, 3, 4, 1, 8, 1, 7, 2, 4, 3, 6, 5, 7, 0, 5, 7, 9, 3, 2, 4]).reshape(4, 5)
# Write your code here.
arr_2 = arr_2 - np.sort(arr_2, axis=0)[1, :]
print(arr_2)

[[ 0 -2  1  0  4]
 [-1  2 -1  3 -1]
 [ 4  0  4 -1  1]
 [ 5  4  0  1  0]]


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 3:</b>
<p>An array has been defined in the cell below.</p>
    
```python
arr_3 = np.arange(36).reshape(6, 6)
```

<p>Write the code to use the <b>Index</b> of <code>arr_3</code> to filter specific elements and assign the filtered elements to a new array <code>answer_3</code>. If you print <code>answer_3</code>, the expected output is shown as below.</p>
    
```
[[15 16 17]
 [21 22 23]
 [27 28 29]]
```

</div>

In [ ]:
###ANSWER(3)
arr_3 = np.arange(36).reshape(6, 6)
answer_3 = arr_3[2:5, 3:] # Write your code here.
print(answer_3)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 4:</b>
<p>Create a $6\times6$ array and assign the result to an array <code>arr_4</code>. If you print <code>arr_4</code>, the expected output is shown as below.</p>
    
```
[[1 0 0 0 0 1]
 [0 1 0 0 1 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 1 0 0 1 0]
 [1 0 0 0 0 1]]
```

</div>

In [ ]:
###ANSWER(4)
arr_4 = (np.eye(6)[:,::-1]+np.eye(6)).astype(int)# Write your code here.
print(arr_4)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 5:</b>
<p>An array has been defined in the cell below.</p>

```python
arr_5 = np.array([2, 3, 4, 1, 8, 6, 7, 2, 4, 3, 6, 4]).reshape(3, 2, 2)    
```
    
<p>Replace the numbers that are larger than 5 in the array with 1 and the numbers that are smaller than 5 with 0, and assign the result to the variable <code>arr_5</code>. If you print <code>arr_5</code>, the expected output is shown as below.</p>
    
```
[[[0 0]
  [0 0]]

 [[1 1]
  [1 0]]

 [[0 0]
  [1 0]]]
```

</div>

In [ ]:
###ANSWER(5)
arr_5 = np.array([2, 3, 4, 1, 8, 6, 7, 2, 4, 3, 6, 4]).reshape(3, 2, 2)
# Write your code here.
arr_5 = np.where(arr_5 > 5, 1, 0)
print(arr_5)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 6:</b>
<p>An array has been defined in the cell below.</p>

```python
arr_6 = np.array([8, np.nan, 3, 1, np.nan, np.nan, 4, 6, 8, np.nan, np.nan, 4, 3, 4, 7]).reshape(3, 5)
```    
    
<p>Fill the NaN values with 0 and assign the result to the variable <code>arr_6</code>. If you print <code>arr_6</code>, the expected output is shown as below.</p>
    
```
[[8. 0. 3. 1. 0.]
 [0. 4. 6. 8. 0.]
 [0. 4. 3. 4. 7.]]
```

</div>

In [ ]:
###ANSWER(6)
arr_6 = np.array([8, np.nan, 3, 1, np.nan, np.nan, 4, 6, 8, np.nan, np.nan, 4, 3, 4, 7]).reshape(3, 5)
# Write your code here.
arr_6 = np.array([8, np.nan, 3, 1, np.nan, np.nan, 4, 6, 8, np.nan, np.nan, 4, 3, 4, 7]).reshape(3, 5)
arr_6[np.isnan(arr_6)] = 0
print(arr_6)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 7:</b>
<p>An array has been defined in the cell below.</p>
    
```python
arr_7 = np.array([-1, 3, -6, 6, -8, 5, 7, 2, -6, -3]).reshape(5,2)
```

<p>Replace each element with its absolute value and assign the result to the variable <code>arr_7</code>. If you print <code>arr_7</code>, the expected output is shown as below.</p>
    
```
[[1 3]
 [6 6]
 [8 5]
 [7 2]
 [6 3]]
```

</div>

In [ ]:
###ANSWER(7)
arr_7 = np.array([-1, 3, -6, 6, -8, 5, 7, 2, -6, -3]).reshape(5,2)
# Write your code here.
arr_7 = np.abs(arr_7)
print(arr_7)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 8:</b>
<p>An array has been defined in the cell below.</p>
    
```python
arr_8 = np.array([5, 12, 4, 7, 3, 12, 7, 8, 9, 3, 4, 5, 7, 14, 5, 7, 10, 3, 2, 13]).reshape(4, 5)    
```
    
<p>For each row in <code>arr_8</code>, get the index of the maximum element, and assign the result to a 1-d array <code>answer_8</code>. If you print <code>answer_8</code>, the expected output is shown as below.</p>
    
```
[1 0 3 4]
```

</div>

In [ ]:
###ANSWER(8)
arr_8 = np.array([5, 12, 4, 7, 3, 12, 7, 8, 9, 3, 4, 5, 7, 14, 5, 7, 10, 3, 2, 13]).reshape(4, 5)
answer_8 = np.argmax(arr_8, axis=1) # Write your code here.
print(answer_8)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>biatch 9:</b>
<p>An array has been defined in the cell below.</p>
    
```python
arr_9 = np.array([2, 3, 4, 1, 8, 9, 2, 2, 4, 3, 6, 9, 2, 3, 4, 6, 8, 9]).reshape(3, 6)    
```
<p>Extract the indices of columns with unequal numbers (i.e. not all elements in the column are the same) and assign the result to a 1-d array <code>answer_9</code>. If you print <code>answer_9</code>, the expected output is shown as below.</p>
    
```
[0 2 5]
```

<p>*Please note that the starting index is <b>0</b> (i.e. the index for the first column is 0).</p>    
</div>

In [10]:
###ANSWER(9)
arr_9 = np.array([2, 3, 4, 1, 8, 9, 2, 2, 4, 3, 6, 9, 2, 3, 4, 6, 8, 9]).reshape(3, 6)
answer_9 = np.where([len(np.unique(i))==1 for i in arr_9.transpose()])[0] 

arr_9 = np.array([2, 3, 4, 1, 8, 9, 2, 2, 4, 3, 6, 9, 2, 3, 4, 6, 8, 9]).reshape(3, 6)
print(arr_9)

arr_9.transpose()

[[2 3 4 1 8 9]
 [2 2 4 3 6 9]
 [2 3 4 6 8 9]]


array([[2, 2, 2],
       [3, 2, 3],
       [4, 4, 4],
       [1, 3, 6],
       [8, 6, 8],
       [9, 9, 9]])

In [11]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 10:</b>
<p>Define a function <code><b>check_range</b></code> which takes three arguments: an array of numbers and two numbers (<code>num_1</code> and <code>num_2</code>). The function would <b>return</b> the number of elements in the array that are greater than or equal to <code>num_1</code> and smaller than or equal to <code>num_2</code>.</p>
<br>
<p>If you execute <code><b>check_range(np.array([3, 3, 5, 1, 7, 9, 2, 4, 4]).reshape(3, 3),3,6)</b></code>, the return value is <code>5</code>.     
<p>If you execute <code><b>check_range(np.array([1, 2, 3, 4]),2,3)</b></code>, the return value is <code>2</code>.  
<p>If you execute <code><b>check_range(np.array([[1, 2, 3, 4], [1, 2, 3, 4]]),2,3)</b></code>, the return value is <code>4</code>.
</div>

In [ ]:
###ANSWER(10)
# Write your code here.
def check_range(arr_num, int_1, int_2):
    return ((arr_num>=int_1)&(arr_num<=int_2)).sum()

In [ ]:
#Please leave this cell blank.