<div class="image">

  <img style="float: right;" src="https://dx5i3n065oxey.cloudfront.net/platform/4186/assets/logo.png?v=2e76f927-9482-4bfb-9092-d9a0b595cd2c" width="45%" align="right">
      <h4>
          <p style="font-size:20pt">Programming for Business Analytics</p>
          <p style="font-size:15pt">Q6 Practice 1</p>
      </h4>
</div>

- Make sure you have executed the code in the cell below.
- Make sure you read the questions carefully and follow the instructions.
- Make sure you put the answers in the Answer cells.
- Please do not put your answers in comments (after #).
- Please do not add any new cells between the Question and Answer cells.
- Please do not change the names of the variables in Answer cells.
- Please do not assign the expected result directly to the variable.
- Please do not change the pre-defined variables.

In [1]:
#Please import numpy and make sure your Jupyter Notebook environment is running a Python 3 kernel 
import numpy as np
import IPython
assert IPython.version_info[0] >= 3, "Your version of IPython is too old, please update it."
%autosave 120

Autosaving every 120 seconds


<div class="alert alert-warning">
<b>QUESTION 1:</b>
<p>An array has been defined below.</p>

```python
arr_1 = np.array([[ 2, 10,  8,  7],
                  [20, 13,  5,  2],
                  [17, 14,  1,  3],
                  [ 9, 11, 17, 10],
                  [ 5,  8,  2, 14]])
```

<p>Write code to sort the values in each column in descending order and assign the new array to variable <code>answer_1</code>. If you print <code>answer_1</code>, the expected output is shown as below.</p>
    
```
[[20 14 17 14]
 [17 13  8 10]
 [ 9 11  5  7]
 [ 5 10  2  3]
 [ 2  8  1  2]]
```

</div>

In [2]:
###ANSWER(1)
arr_1 = np.array([[ 2, 10,  8,  7],
                  [20, 13,  5,  2],
                  [17, 14,  1,  3],
                  [ 9, 11, 17, 10],
                  [ 5,  8,  2, 14]])
# Write your code here.

In [28]:
import pandas as pf
arr_1 = pf.DataFrame(arr_1)
arr_1['sum'] = arr_1.apply(lambda x: x.sum())

arr_1.loc[0,3]
arr_1

0   1   2     3   sum
0   2  10   8   NaN  53.0
1  20  13   5   2.0  56.0
2  17  14   1   3.0  33.0
3   9  11  17  10.0  36.0
4   5   8   2  14.0   NaN

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 2:</b>
<p>An array has been defined below.</p>

```python
arr_2 = np.array([[[-1, 9, 10], [3, -2, 9]], [[-2, -7, 2], [-3, 9, 10]]])
```

<p>Write code to replace the negative numbers in <code>arr_2</code> with 0 and assign the result to the variable <code>arr_2</code>. If you print <code>arr_2</code>, the expected output is shown as below.</p>
    
```
[[[ 0  9 10]
  [ 3  0  9]]

 [[ 0  0  2]
  [ 0  9 10]]]
```

</div>

In [ ]:
###ANSWER(2)
arr_2 = np.array([[[-1, 9, 10], [3, -2, 9]], [[-2, -7, 2], [-3, 9, 10]]])
# Write your code here.
arr_2[arr_2<0] = 0
print(arr_2)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 3:</b>
<p>An array has been defined.</p>

```python
arr_3 = np.arange(25).reshape(5, 5)
```

<p>By indexing and/or slicing <code>arr_3</code>, create a new array called <code>answer_3</code>. Print <code>answer_3</code>, the expected output is shown below.</p>
    
```
[[11 12 13]
 [16 17 18]]
```

</div>

In [ ]:
###ANSWER(3)
arr_3 = np.arange(25).reshape(5, 5)
answer_3 = arr_3[2:4, 1:4] # Write your code here.
print(answer_3)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 4:</b>
<p>Create a $10\times10$ array with 2's on the border and 5's inside and assign the array to the variable <code>answer_4</code>. If you print <code>answer_4</code>, the expected output is shown as below.</p>
    
```
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 5. 5. 5. 5. 5. 5. 5. 5. 2.]
 [2. 5. 5. 5. 5. 5. 5. 5. 5. 2.]
 [2. 5. 5. 5. 5. 5. 5. 5. 5. 2.]
 [2. 5. 5. 5. 5. 5. 5. 5. 5. 2.]
 [2. 5. 5. 5. 5. 5. 5. 5. 5. 2.]
 [2. 5. 5. 5. 5. 5. 5. 5. 5. 2.]
 [2. 5. 5. 5. 5. 5. 5. 5. 5. 2.]
 [2. 5. 5. 5. 5. 5. 5. 5. 5. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]
```

</div>

In [ ]:
###ANSWER(4)
answer_4 = np.ones((10,10))*2
answer_4[1:9,1:9] = 5
print(answer_4)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 5:</b>
<p>An array has been defined in the cell below.</p>

```python
arr_5 = np.arange(21).reshape(7,3)
```

<p>Replace each odd number in the array with the square of it and assign the result to the variable <code>arr_5</code>. If you print <code>arr_5</code>, the expected output is shown as below.</p>
    
```
[[  0   1   2]
 [  9   4  25]
 [  6  49   8]
 [ 81  10 121]
 [ 12 169  14]
 [225  16 289]
 [ 18 361  20]]
```

</div>

In [ ]:
###ANSWER(5)
arr_5 = np.arange(21).reshape(7,3)
# Write your code here.
arr_5[arr_5%2==1] = np.square(arr_5[arr_5%2==1])
print(arr_5)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 6:</b>
<p>An array has been defined in the cell below.</p>

```python
arr_6 = np.arange(20).reshape(4,5)
```

<p>For each row in the array, substract the mean of that row and assign the result to the variable <code>arr_6</code>. If you print <code>arr_6</code>, the expected output is shown as below.</p>
    
```
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
```

</div>

In [2]:
###ANSWER(6)
import numpy as np
arr_6 = np.arange(20).reshape(4,5)
arr_6 = arr_6.transpose() - arr_6.mean(axis=1) # Write your code here.
print(arr_6)

[[-2. -2. -2. -2.]
 [-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]]


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 7:</b>
<p>An array has been defined in the cell below.</p>

```python
arr_7 = = np.array([[10,2,3],[1,3,3],[2,34,4],[5,4,3]])
```

<p>For each row in the array, apply the following formula:</p>
$x_{1}\times2 + x_{2}\times5 + x_{3}\times3$
<p>For instance, if you apply the formula to the first row, you will get 39 ($10\times2 + 2\times5 + 3\times3$).</p> 
<p>Assign the result to a one-dimensional array <code>answer_7</code>. If you print <code>answer_7</code>, the expected output is shown as below.</p>
    
```
[ 39  26 186  39]
```

</div>

In [ ]:
###ANSWER(7)
arr_7 = np.array([[10,2,3],[1,3,3],[2,34,4],[5,4,3]])
answer_7 = (arr_7*[2,5,3]).sum(axis=1) # Write your code here.
print(answer_7)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 8:</b>
<p>An array has been defined in the cell below.</p>

```python
arr_8 = np.arange(32).reshape(8,4)
```

<p>For each column in the array, calculate the cumulative sum of elements. The result should still be a $8\times4$ array. Assign the array to the variable <code>answer_8</code>. If you print <code>answer_8</code>, the expected output is shown as below.</p>
    
```
[[  0   1   2   3]
 [  4   6   8  10]
 [ 12  15  18  21]
 [ 24  28  32  36]
 [ 40  45  50  55]
 [ 60  66  72  78]
 [ 84  91  98 105]
 [112 120 128 136]]
```

</div>

In [ ]:
###ANSWER(8)
arr_8 = np.arange(32).reshape(8,4)
answer_8 = arr_8.cumsum(axis=0) # Write your code here.
print(answer_8)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 9:</b>
<p>An array has been defined in the cell below.</p>

```python
arr_9 = np.arange(36).reshape(12,3)
```

<p>Select a subset of all even rows (2nd, 4th, 6th ...) from <code>arr_9</code> and assign the new array to the variable <code>answer_9</code>. If you print <code>answer_9</code>, the expected output is shown as below.</p>
    
```
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]
```

</div>

In [ ]:
###ANSWER(9)
arr_9 = np.arange(36).reshape(12,3)
answer_9 = arr_9[1::2, :] # Write your code here.
print(answer_9)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 10:</b>
<p>Define a function <code><b>check_arr_nan</b></code> which takes an array as the argument. The function would <b>return</b> the number of NaN values in the array.</p>
<br>
<p>If you execute <code><b>check_arr_nan(np.array([-1, np.nan, 10, np.nan]))</b></code>, the return value is <code>2</code>.  
<p>If you execute <code><b>check_arr_nan(np.array([[-1, np.nan, 10], [3, np.nan, 9],[np.nan, np.nan, 2]]))</b></code>, the return value is <code>4</code>.    
<p>If you execute <code><b>check_arr_nan(np.array([[[-1, np.nan, 10], [3, np.nan, 9]], [[-2, -7, 2], [-3, np.nan, 10]]]))</b></code>, the return value is <code>3</code>. 
</div>

In [ ]:
###ANSWER(10)
# Write your code here.
def check_arr_nan(arr):
    return sum(np.isnan(arr).flatten())

In [ ]:
#Please leave this cell blank.