<div class="image">

  <img style="float: right;" src="https://dx5i3n065oxey.cloudfront.net/platform/4186/assets/logo.png?v=2e76f927-9482-4bfb-9092-d9a0b595cd2c" width="45%" align="right">
      <h4>
          <p style="font-size:20pt">Programming for Business Analytics</p>
          <p style="font-size:15pt">Q8 Practice 2</p>
      </h4>
</div>

- Make sure you have executed the code in the cell below.
- Make sure you read the questions carefully and follow the instructions.
- Make sure you put the answers in the Answer cells.
- Please do not put your answers in comments (after #).
- Please do not add any new cells between the Question and Answer cells.
- Please do not change the names of the variables in Answer cells.
- Please do not assign the expected result directly to the variable.
- Please do not change the pre-defined variables.

In [ ]:
#Please import packages and make sure your Jupyter Notebook environment is running a Python 3 kernel 
import numpy as np
import pandas as pd
import IPython
assert IPython.version_info[0] >= 3, "Your version of IPython is too old, please update it."
%autosave 120

<div class="alert alert-warning"> 
<b>QUESTION 1:</b> 
    
<p>Which one of the following statements is wrong?</p>
<p> a) Tuples are immutable objects. </p>
<p> b) Sets can be indexed. </p>
<p> c) A pure function would return values that depend only on its arguments. </p>
<p> d) A DataFrame can be transposed. </p>

</div>

In [ ]:
###ANSWER(1). Please assign the letter representing the correct answer to the variable 
### (write it down between the "")
answer_1 = "b"

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 2:</b>
<p>A list called <code>nums</code> has been defined. </p>

```python
nums = [1, 2, 5, 7, -3, -9, 2, -10, 2, 7, 9, 3, -1, 2, 5, 8, 9, -2, 4, 5]    
```
    
<p>Write <b>ONE LINE</b> of code to replace any positive number with its squared value and assign the result to <code>nums</code>. Print <code>nums</code>, the expected output is shown below. </p>

```
[1, 4, 25, 49, -3, -9, 4, -10, 4, 49, 81, 9, -1, 4, 25, 64, 81, -2, 16, 25]
```
</div>

In [ ]:
###ANSWER(2)
nums = [1, 2, 5, 7, -3, -9, 2, -10, 2, 7, 9, 3, -1, 2, 5, 8, 9, -2, 4, 5]
# Write your code here
nums = [i**2 if i>0 else i for i in nums]
print(nums)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 3:</b>
<p>An array has been defined.</p>
    
```python
arr_3 = np.array([6, 3, 4, 7, 9, 4, 7, 8, 9, 3, 4, 5, 7, 3, 5, 7, 7, 3, 2, 13]).reshape(4, 5)    
```
    
<p>Calculate the cumulative sum of the elements over columns for each of the 4 rows, and assign the result to an array <code>answer_3</code>. If we print <code>answer_3</code>, the expected output is shown below.</p>
    
```
[[ 6  9 13 20 29]
 [ 4 11 19 28 31]
 [ 4  9 16 19 24]
 [ 7 14 17 19 32]]
```

</div>

In [ ]:
###ANSWER(3)
arr_3 = np.array([6, 3, 4, 7, 9, 4, 7, 8, 9, 3, 4, 5, 7, 3, 5, 7, 7, 3, 2, 13]).reshape(4, 5)
answer_3 = arr_3.cumsum(axis=1) # Write your code here
print(answer_3)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 4: </b> 
<p>A list has been defined. </p>
 
```python
list_4 = [[3,8,5,7],[2,6,3],[7,8,9,5,6,3],[2,3,1],[7,8,4,9]]    
```
    
<p>Write <b>ONE LINE</b> of code to sort each sublist in <b>descending</b> order and assign the result to <code>list_4</code>. Print <code>list_4</code>, the expected output is shown below. </p>

```
[[8, 7, 5, 3], [6, 3, 2], [9, 8, 7, 6, 5, 3], [3, 2, 1], [9, 8, 7, 4]]
```
</div>

In [ ]:
###ANSWER(4)
list_4 = [[3,8,5,7],[2,6,3],[7,8,9,5,6,3],[2,3,1],[7,8,4,9]]
list_4 = [sorted(i, reverse=True) for i in list_4] # Write your code here
print(list_4)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 5: </b> 
<p>A dictionary has been defined. </p>
    
```python
dict_5 = {'a':300, 'b':150, 'c':250, 'd':134, 'e':156, 'f':199, 'g': 256, 'h':388, 'i':132, 'j':240}    
```
    
<p>Write code to delete the elements where the corresponding values are larger than 200 and assign the result to <code>dict_5</code>. Print <code>dict_5</code>, the expected output is shown below.</p>

```
{'b': 150, 'd': 134, 'e': 156, 'f': 199, 'i': 132}
```
</div>

In [ ]:
###ANSWER(5)
dict_5 = {'a':300, 'b':150, 'c':250, 'd':134, 'e':156, 'f':199, 'g': 256, 'h':388, 'i':132, 'j':240}
# Write your code here
dict_5 = {k:v for k,v in dict_5.items() if v<=200}
print(dict_5)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 6: </b> 
<p>Create a $6\times6$ array called <code>arr_6</code>. Print <code>arr_6</code>, the expected output is shown below.</p>
    
```
[[6 0 0 0 0 6]
 [0 6 0 0 6 0]
 [0 0 6 6 0 0]
 [0 0 6 6 0 0]
 [0 6 0 0 6 0]
 [6 0 0 0 0 6]]
```

</div>

In [ ]:
###ANSWER(6)
arr_6 = (np.eye(6)[:,::-1]+np.eye(6)).astype(int)*6 # Write your code here
print(arr_6)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 7:</b>
<p>An array has been defined.</p>
    
```python
arr_7 = np.array([7, np.nan, 3, 1, np.nan, np.nan, 10, 7, 8, 3, np.nan, 9]).reshape(3, 4)
```
    
<p>Fill the NaN values with the mean (integer) of all the other non-NaN values and assign the result to <code>arr_7</code>. Print <code>arr_7</code>, the expected output is shown below.</p>
    
```
[[ 7  6  3  1]
 [ 6  6 10  7]
 [ 8  3  6  9]]
```

</div>

In [ ]:
###ANSWER(7)
arr_7 = np.array([7, np.nan, 3, 1, np.nan, np.nan, 10, 7, 8, 3, np.nan, 9]).reshape(3, 4)
# Write your code here
arr_7[np.isnan(arr_7)] = np.mean(arr_7[~np.isnan(arr_7)])
arr_7 = arr_7.astype(int)
print(arr_7)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 8:</b>
<p>A list has been defined. </p>
    
```python
list_8 = ['Birmingham', 'Shenzhen', 'San Francisco', 'Da Nang', 'Accra', 'Jerusalem', 'Tema', 'Urumqi']    
```
    
<p>Write code to sort the list in descending order by the length of the strings. Print <code>list_8</code>, the expected output is shown below.</p>
    
```
['San Francisco', 'Birmingham', 'Jerusalem', 'Shenzhen', 'Da Nang', 'Urumqi', 'Accra', 'Tema']
```
</div>

In [ ]:
###ANSWER(8)
list_8 = ['Birmingham', 'Shenzhen', 'San Francisco', 'Da Nang', 'Accra', 'Jerusalem', 'Tema', 'Urumqi']
# Write your code here
list_8.sort(reverse=True, key=lambda x:len(x))
print(list_8)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 9:</b>

<p>A list has been defined. </p>

```python
list_9 = ['Finley', 'Minnie', 'Shadow', 'Crystal', 'Coral']    
```
    
<p>Use <code><b>join</b></code> method to join the list of strings into a string, and assign the result to <code>str_9</code>. Print <code>str_9</code>, the expected output is shown below.</p>
    
```
Finley, Minnie, Shadow, Crystal, Coral
```
</div>

In [ ]:
###ANSWER(9)
list_9 = ['Finley', 'Minnie', 'Shadow', 'Crystal', 'Coral']
str_9 = ', '.join(list_9) # Write your code here
print(str_9)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 10:</b>
<p>A dictionary has been defined. </p>
 
```python
dict_10 = {'Liam':20, 'Olivia':20, 'Emma':20, 'Charlotte':20, 'Elijah':20, 'William':20, 'Benjamin':20, 
           'Alexander':20, 'Anthony':20, 'Abigail':20, 'Beatrice':20, 'Ben':20, 'James':20, 'Sophia':20, 
           'Anna':20, 'Bella':20, 'Lucas':20, 'Connor':20}    
```
    
<p>For items in the dictionary, if the key starts with <code>A</code>, <code>B</code> or <code>C</code>, increase the corresponding value by <code>1</code> and assign the result to <code>dict_10</code>. Print <code>dict_10</code>, the expected output is shown below. </p>
    
```    
{'Liam': 20, 'Olivia': 20, 'Emma': 20, 'Charlotte': 21, 'Elijah': 20, 'William': 20, 'Benjamin': 21, 'Alexander': 21, 'Anthony': 21, 'Abigail': 21, 'Beatrice': 21, 'Ben': 21, 'James': 20, 'Sophia': 20, 'Anna': 21, 'Bella': 21, 'Lucas': 20, 'Connor': 21}
```
</div>

In [ ]:
###ANSWER(10)
dict_10 = {'Liam':20, 'Olivia':20, 'Emma':20, 'Charlotte':20, 'Elijah':20, 'William':20, 'Benjamin':20, 
           'Alexander':20, 'Anthony':20, 'Abigail':20, 'Beatrice':20, 'Ben':20, 'James':20, 'Sophia':20, 
           'Anna':20, 'Bella':20, 'Lucas':20, 'Connor':20}
# Write your code here
dict_10 = {k:v+1 if k[0] in ['A', 'B', 'C'] else v for k,v in dict_10.items()}
print(dict_10)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 11:</b>

<p>A list has been defined. </p>
    
```python
list_11 = ['Liam', 'Olivia', 'Emma', 'Charlotte', 'Elijah', 'William', 'Benjamin', 'Alexander', 
           'Anthony', 'Abigail', 'Beatrice', 'Ben', 'James', 'Sophia', 'Anna', 'Bella', 'Lucas', 'Connor']    
```
    
<p>Use <code><b>filter</b></code> function to remove the elements with length larger than <code>5</code> and assign the result to <code>list_11</code>. Print <code>list_11</code>, the expected output is <code>['Liam', 'Emma', 'Ben', 'James', 'Anna', 'Bella', 'Lucas']</code>.</p>
</div>

In [ ]:
###ANSWER(11)
list_11 = ['Liam', 'Olivia', 'Emma', 'Charlotte', 'Elijah', 'William', 'Benjamin', 'Alexander', 
           'Anthony', 'Abigail', 'Beatrice', 'Ben', 'James', 'Sophia', 'Anna', 'Bella', 'Lucas', 'Connor']
list_11 = list(filter(lambda x:len(x)<=5, list_11)) # Write your code here
print(list_11)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 12:</b>
<p>An array has been defined.</p>
    
```python
arr_12  = np.array([[12,  6,  9,  4],
                    [13,  7,  5,  8],
                    [28, 14,  1,  3],
                    [ 9, 10, 11, 11],
                    [ 6,  8,  2, 25]])    
```

<p>Write code to sort the values in each column in descending order and assign the result to <code>arr_12</code>. Print <code>arr_12</code>, the expected output is shown below.</p>
    
```
[[28 14 11 25]
 [13 10  9 11]
 [12  8  5  8]
 [ 9  7  2  4]
 [ 6  6  1  3]]
```
</div>

In [ ]:
###ANSWER(12)
arr_12  = np.array([[12,  6,  9,  4],
                    [13,  7,  5,  8],
                    [28, 14,  1,  3],
                    [ 9, 10, 11, 11],
                    [ 6,  8,  2, 25]])
# Write your code here
arr_12.sort(axis=0)
arr_12 = arr_12[::-1]
print(arr_12)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 13:</b>
<p>Two lists have been defined. </p>
    
```python
list_1 = [1, 3, 5, 7, 9, 7, 3, 6, 7, 8]
list_2 = [1, 3, 7, 10, 21, 11, 3, 7, 14]    
```
    
<p>Find the common items from <code>list_1</code> and <code>list_2</code> and assign the result to <code>list_3</code>. Print <code>list_3</code>, the expected output would is <code>[1, 3, 7]</code>.</p>
</div>

In [ ]:
###ANSWER(13)
list_1 = [1, 3, 5, 7, 9, 7, 3, 6, 7, 8]
list_2 = [1, 3, 7, 10, 21, 11, 3, 7, 14]
# Write your code here
list_3 = list(set(list_1)&set(list_2))
print(list_3)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 14:</b>
<p>Define a function called <code><b>remove_digits</b></code> which takes a string as the input argument. The function would remove all the numerical digits from the string and <b>return</b> the result. If the user attempts to call the function with the argument not being a string, the function should raise an <code>AssertionError</code> with the message <code>Invalid input</code>.</p>
<br>
<p>Execute <code><b>remove_digits('4a3ac')</b></code>, the expected output is <code>'aac'</code>.</p>
<p>Execute <code><b>remove_digits('ano45th3e32r')</b></code>, the expected output is <code>'another'</code>.</p>
<p>Execute <code><b>remove_digits(20)</b></code>, an <code>AssertionError</code> is raised with the message <code>Invalid input</code>.</p>
</div>

In [ ]:
###ANSWER(14)
# Write your code here
def remove_digits(string):
    assert type(string)==str, 'Invalid input'
    return ''.join([i for i in string if not i.isdigit()])

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 15:</b>
<p>Define a function called <code><b>flatten_list</b></code> which takes a list as the input argument. The function would flatten the list until there is no sublist in it and <b>return</b> the list. </p>
<br>
<p>Execute <code><b>flatten_list([1,2,3,4,5,6,7,8,9,10])</b></code>, the expected output is <code>[1,2,3,4,5,6,7,8,9,10]</code>.</p>
<p>Execute <code><b>flatten_list([1,[2],3,4,5,[6,7,8],9,10])</b></code>, the expected output is <code>[1,2,3,4,5,6,7,8,9,10]</code>.</p>
<p>Execute <code><b>flatten_list([1,[2,3],4,[[5,[[6],7]],[8,9],10]])</b></code>, the expected output is <code>[1,2,3,4,5,6,7,8,9,10]</code>.</p>
<br>
<p>*Note: the function should be able to work with any levels of nested list.</p>
</div>

In [ ]:
###ANSWER(15)
# Write your code here
def flatten_list(a_list):
    if a_list ==[]:
        return a_list
    if isinstance(a_list[0], list):
        return flatten_list(a_list[0]) + flatten_list(a_list[1:])
    return a_list[:1]+flatten_list(a_list[1:])

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 16:</b>
<p>A DataFrame <code>df</code> has been defined by reading a CSV file. </p>

```python
df = pd.read_csv('./Quiz8_files/iris.csv')  
```
   
<p>For each column name, replace the space between the two words with an underscore. Display the first 5 rows of <code>df</code>, the expected output is shown below.</p>
<img src="./Quiz8_files_2/Q16.png" width="40%">
    
</div>

In [ ]:
###ANSWER(16)
df = pd.read_csv('./Quiz8_files_2/iris.csv')
# Write your code here
df.columns = [i.replace(' ','_') for i in df.columns]
display(df.head())

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 17:</b>
<p>The DataFrame <code>df</code> has been defined in the previous question. </p>
<p>Create a new column called <code>Target</code> in which the first 50 rows are <code>setosa</code>, the second 50 rows are <code>versicolor</code> and the last 50 rows are <code>virginica</code>. Display the first 5 rows of <code>df</code>, the expected output is shown below.</p>
<img src="./Quiz8_files_2/Q17.png" width="40%">
    
</div>

In [ ]:
###ANSWER(17)
# Write your code here
df['Target'] = ['setosa']*50 + ['versicolor']*50 + ['virginica']*50
display(df.head())

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 18:</b>
<p>The DataFrame <code>df</code> has been defined in the previous question. </p>
<p>Fill the missing data in column <code>Sepal_Length</code> with the mean value (round to the <b>first</b> decimal place) of the corresponding <code>Target</code> class. Display the first 5 rows of <code>df</code>, the expected output is shown below.</p>
<img src="./Quiz8_files_2/Q18.png" width="40%">

</div>

In [ ]:
###ANSWER(18)
# Write your code here
for i in df.Target.unique():
    df.loc[(df.Target==i)&(df.Sepal_Length.isnull()), 'Sepal_Length'] = round(
        df[df.Target==i].Sepal_Length.mean(), 1)
display(df.head())

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 19:</b>
<p>The DataFrame <code>df</code> has been defined in the previous question. </p>
<p>Separate the data in column <code>Petal_Length</code> into 3 bins: 0 to 3 (including 3), 3 to 5 (including 5) and 5 to 10 (including 10). The corresponding bin names are <code>S</code>, <code>M</code> and <code>L</code>. Replace the column with the bin names. Display the first 5 rows of <code>df</code>, the expected output is shown below.</p>
<img src="./Quiz8_files_2/Q19.png" width="40%">

</div>

In [ ]:
###ANSWER(19)
# Write your code here
df.Petal_Length = pd.cut(df.Petal_Length, [0, 3, 5,10],labels=['S','M','L'])
display(df.head())

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 20:</b>
<p>The DataFrame <code>df</code> has been defined in the previous question. </p>
<p>Capitalize the <b>first 3</b> letters of the word from column <code>Target</code>. Display the first 5 rows of <code>df</code>, the expected output is shown below.</p>
<img src="./Quiz8_files_2/Q20.png" width="40%">
</div>

In [ ]:
###ANSWER(20)
# Write your code here
df.Target = df.Target.apply(lambda x:x[:3].upper()+x[3:])
display(df.head())

In [ ]:
#Please leave this cell blank.