<div class="image">

  <img style="float: right;" src="https://dx5i3n065oxey.cloudfront.net/platform/4186/assets/logo.png?v=2e76f927-9482-4bfb-9092-d9a0b595cd2c" width="45%" align="right">
      <h4>
          <p style="font-size:20pt">Programming for Business Analytics</p>
          <p style="font-size:15pt">Q8 Practice 1</p>
      </h4>
</div>

- Make sure you have executed the code in the cell below.
- Make sure you read the questions carefully and follow the instructions.
- Make sure you put the answers in the Answer cells.
- Please do not put your answers in comments (after #).
- Please do not add any new cells between the Question and Answer cells.
- Please do not change the names of the variables in Answer cells.
- Please do not assign the expected result directly to the variable.
- Please do not change the pre-defined variables.

In [ ]:
#Please import packages and make sure your Jupyter Notebook environment is running a Python 3 kernel 
import numpy as np
import pandas as pd
import IPython
assert IPython.version_info[0] >= 3, "Your version of IPython is too old, please update it."
%autosave 120

<div class="alert alert-warning"> 
<b>QUESTION 1:</b> 
<p>Which two of the following data types are both <b>Unordered</b>? </p>
<p> a) List & Set </p>
<p> b) List & Tuple </p>
<p> c) Tuple & Dictionary</p>
<p> d) Dictionary & Set</p>

</div>

In [ ]:
###ANSWER(1). Please assign the letter representing the correct answer to the variable 
### (write it down between the "")

answer_1 = "" # YOUR ANSWER SHOULD BE BETWEEN ""

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 2:</b>
<p>Two sets have been defined. </p>

```python
first_set = {1,2,3,4,5,6}
second_set = {2,4,6,7,8}    
```
    
<p>Find elements that only appear in <code>first_set</code>, not in <code>second_set</code> and assign the results to a new list <code>new_list</code>. Print <code>new_list</code>, the expected output is <code>[1, 3, 5]</code>.</p>
</div>

In [ ]:
###ANSWER(2)
first_set = {1,2,3,4,5,6}
second_set = {2,4,6,7,8}
new_list = # Write your code here
print(new_list)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 3:</b>
<p>Two arrays have been defined. </p>

```python
arr_1 = np.array([[1, 3, 5], [7, 9, 11]])
arr_2 = np.array([[2, 4, 6], [8, 10, 12]])    
```    
    
<p>Add <code>arr_1</code> and <code>arr_2</code> element by element and assign the new array <code>arr_3</code>. Print <code>arr_3</code>, the expected output is shown below.</p>

``` 
[[ 3  7 11]
 [15 19 23]]
```
</div>

In [ ]:
###ANSWER(3)
arr_1 = np.array([[1, 3, 5], [7, 9, 11]])
arr_2 = np.array([[2, 4, 6], [8, 10, 12]])
arr_3 = # Write your code here
print(arr_3)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 4: </b> 
<p>Define a function called <code><b>function_4</b></code> which takes a positive integer <code>n</code> as the argument. The function would calculate the value of $ \prod_{x=1}^{n} \frac{1}{x} $ and <b>return</b> the result.</p>
<p>$ \prod_{x=1}^{n} \frac{1}{x} = \underbrace{1 \cdot  \frac{1}{2} \cdot \frac{1}{3} \cdot \frac{1}{4} \cdot \frac{1}{5} \cdots}_{\text {from 1/1 to 1/n}} $</p>
<br>
<p>Execute <code><b>function_4(1)</b></code>, the expected output is <code>1</code>.</p>
<p>Execute <code><b>function_4(4)</b></code>, the expected output is as below:</p>
<p>$ \prod_{n=1}^{4} \frac{1}{n} = 1 \cdot  \frac{1}{2} \cdot \frac{1}{3} \cdot \frac{1}{4}=0.041666666666666664 $
</p>
</div>

In [ ]:
###ANSWER(4)
# Write your code here
def function_4


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 5: </b> 
<p>Define a function called <code><b>test_palindrome</b></code> which takes a string as the argument. The function would <b>print</b> <code>Palindrome!</code> if its argument is a palindrome and <b>print</b> <code>Not a palindrome!</code> otherwise.</p>
<br>
<p>Execute <code><b>test_palindrome('Kik')</b></code>, the expected output is <code>Palindrome!</code>.</p>  
<p>Execute <code><b>test_palindrome('abcd')</b></code>, the expected output is <code>Not a palindrome!</code>.</p> 
<br>
<p>*Note: Palindrome is a word that reads the same backwords and forwards, such as <code>Kik</code>, <code>MadAm</code> or <code>kayak</code>. You should disregard the case of the string in the problem. </p>
</div>

In [ ]:
###ANSWER(5)
# Write your code here
def test_palindrome


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 6: </b> 
<p>Using a <code>while</code> loop, calculate the sum of the positive integers which are less than or equal to 1000 and can't be divided by 7 without a remainder. Assign the result to <code>answer_6</code>. Print <code>answer_6</code>, the expected output is <code>429429</code>.</p>
</div>

In [ ]:
###ANSWER(6)
# Write your code here

print(answer_6)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 7:</b>
<p>A string has been defined. </p>
    
```python
names = 'Olivia, Amelia; Isla, Ava; Grace'  
```
    
<p>Write <b>ONE LINE</b> of code to split the names in the string and turn it into a list <code>name_list</code>. Print <code>name_list</code>, the expected output is <code>['Olivia', 'Amelia', 'Isla', 'Ava', 'Grace']</code>.</p>
</div>

In [ ]:
###ANSWER(7)
names = 'Olivia, Amelia; Isla, Ava; Grace'
name_list = # Write your code here
print(name_list)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 8:</b>

<p>Create a $7\times3$ array called <code>arr_8</code> with integers ranging from 200 to 0 with a step of 10 (in descending order). Print <code>arr_8</code>, the expected output is shown below.</p>

```
[[200 190 180]
 [170 160 150]
 [140 130 120]
 [110 100  90]
 [ 80  70  60]
 [ 50  40  30]
 [ 20  10   0]]
```
</div>

In [ ]:
###ANSWER(8)
arr_8 = # Write your code here
print(arr_8)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 9:</b>

<p>A list has been defined. </p>
    
```python
countries = ['afghanistan', 'Barbados', 'bahrain', 'China', 'cameroon', 'Lesotho', 'Colombia']    
```
    
<p>Write <b>ONE LINE</b> of code to find the indices of the items in <code>countries</code> that start with <code>c</code> or <code>C</code> and assign the result to <code>tar_index</code>. Print <code>tar_index</code>, the expected output is <code>[3, 4, 6]</code>.</p>
</div>

In [ ]:
###ANSWER(9)
countries = ['afghanistan', 'Barbados', 'bahrain', 'China', 'cameroon', 'Lesotho', 'Colombia']
tar_index = # Write your code here
print(tar_index)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 10:</b>

<p>Two dictionaries have been defined. </p>

```python
dict_1 = {'A':1, 'B':2, 'C':4}
dict_2 = {'B':2, 'C':2, 'D':3}    
```
    
<p>Write code to merge the two dictionaries. For the items that have the same keys, you should calculate the sum of the values. Assign the result to <code>dict_merged</code>. Print <code>dict_merged</code>, the expected output is <code>{'A': 1, 'B': 4, 'C': 6, 'D': 3}</code>.</p>
</div>

In [ ]:
###ANSWER(10)
dict_1 = {'A':1, 'B':2, 'C':4}
dict_2 = {'B':2, 'C':2, 'D':3}
# Write your code here

print(dict_merged)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 11:</b>

<p>Three lists have been defined. </p>
    
```python
list_a = [1,32,54,8,9,23,6,98,43,2,7,98]
list_b = [32,3,1,7,98,6,4,6,43,2,13,4]
list_c = [21,4,7,58,12,79,13,34,69,12,4,5]   
```
    
<p>Write <b>ONE LINE</b> of code to find the sum of the elements at the same position in the three lists and assign the result to <code>list_sum</code>. Print <code>list_sum</code>, the expected output is <code>[54, 39, 62, 73, 119, 108, 23, 138, 155, 16, 24, 107]</code>.</p>
</div>

In [ ]:
###ANSWER(11)
list_a = [1,32,54,8,9,23,6,98,43,2,7,98]
list_b = [32,3,1,7,98,6,4,6,43,2,13,4]
list_c = [21,4,7,58,12,79,13,34,69,12,4,5]
list_sum =  # Write your code here
print(list_sum)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 12:</b>

<p>A list called <code>letters</code> has been defined. </p>
    
```python
letters = ['A','U','B','C','D','A','B','D','A','D','B','A','B','D','L','A','B','B','A','B']    
```    
    
<p>Write <b>ONE LINE</b> of code to find all the elements from <code>letters</code> except <code>'A'</code>, <code>'B'</code> and <code>'D'</code> and assign the result to <code>letters_new</code>. Print <code>letters_new</code>, the expected output is <code>['U', 'C', 'L']</code>.</p>
</div>

In [ ]:
###ANSWER(12)
letters = ['A','U','B','C','D','A','B','D','A','D','B','A','B','D','L','A','B','B','A','B']
letters_new =  # Write your code here
print(letters_new)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 13:</b>
<p>Some codes have been given. </p>
    
```python
nums = [2.3233, 1.2355, 3.3371]
msg = "Numbers: { } { } { }".format(nums[0],nums[1],nums[2])   
```    
<p>Fill the gaps in the code so that when printing <code>msg</code>, the expected output is <code>Numbers: 1.24 2.3233 3.3371</code>.</p>
</div>

In [ ]:
###ANSWER(13)
# Please fill the gaps in the code
nums = [2.3233, 1.2355, 3.3371]
msg = "Numbers: { } { } { }".format(nums[0],nums[1],nums[2])
print(msg)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 14:</b>
<p>The factorial of a number is represented by $n!$, which is the product of all the integers from 1 to that number. The equation of calculating the factorial is $n!=1*2*3*...*(n-1)*n$.</p>
<p>For example, $4!=1*2*3*4=24$, $3!=1*2*3=6$.</p> 
<p>$1!=0!=1$.</p>
<br>
<p>Define a function called <code>factorial</code> which takes an integer as the arugment. The function would <b> return</b> the factorial of the argument. If the function is called with a negative integer, it would raise an <code>AssertionError</code> with the message <code>Please call the function with a non-negative integer</code>.</p>
<br>
<p>Execute <code><b>factorial(1)</b></code>, the expected output is <code>1</code>.</p> 
<p>Execute <code><b>factorial(3)</b></code>, the expected output is <code>6</code>.</p> 
<p>Execute <code><b>factorial(-1)</b></code>, an <code>AssertionError</code> is raised with the message <code>Please call the function with a non-negative integer</code>.</p>
</div>

In [ ]:
###ANSWER(14)
# Write your code here
def factorial


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 15:</b>

<p>A list called <code>int_nums</code> has been defined. </p>
    
```python
int_nums = [2, 3, 5, 6, 8, 9, 11, 12, 15, 18]    
```

<p>Use <code><b>filter</b></code> function to remove the even numbers from the list and assign the result to <code>int_nums</code>. Print <code>int_nums</code>, the expected output is <code>[3, 5, 9, 11, 15]</code>.</p>
</div>

In [ ]:
###ANSWER(15)
int_nums = [2, 3, 5, 6, 8, 9, 11, 12, 15, 18]
int_nums = # Write your code here
print(int_nums)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 16:</b>
<p>A list called <code>nums</code> has been defined in the cell below.</p> 

```python
nums = [1, 3, 5, 6, 8]    
```
    
<p>Write <b>ONE LINE</b> of code to sort the list with the ascending order of the absolute difference between the element and number <code>5</code> and assign the result to <code>nums</code>. Print <code>nums</code>, the expected output is <code>[5, 6, 3, 8, 1]</code>.</p>
</div>

In [ ]:
###ANSWER(16)
nums = [1, 3, 5, 6, 8]
nums = # Write your code here
print(nums)

In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 17:</b>
<p>A DataFrame <code>df_sale</code> that contains sales information has been. </p>
    
```python
df_sale = pd.DataFrame(data = {'MANAGER':['Anna', 'Anna', 'Martin', 'Anna', 'Martin', 'Martin', 
                                          'Anna', 'Martin'],
                               'CLIENTS':[2, 7, 5, 5, 4, 5, 8, 5],
                               'AMOUNT':[80.1, 10.2, 10., 80.3, 70., 100.2, 30., 40.5],
                               'SALESPERSON':['Ben', 'Andrew',  'Elisa', 'Kat', 'Tom', 'Bet', 
                                              'Elenore', 'Steve'],
                               'ACTIVE':['Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N']},
                       index = pd.DatetimeIndex(['2020-03-01', '2020-05-01', '2020-03-01', '2020-04-01', 
                                                 '2020-04-01', '2020-05-01', '2020-06-01', '2020-06-01'])) 
```
    
<p>Create a new column called <code>MAN_EMPL_EARNINGS</code> that will show both names of the manager and salesperson next to each other, separated by <code>-</code> and amount of earnings preceded by a <code>+</code> sign, e.g. <code>Anna-Ben+80.0</code>. Display <code>df_sale</code>, the expected output is shown below.</p>

<img src="./Quiz8_files_1/Question17.png" width="60%">

</div>

In [ ]:
###ANSWER(17)
df_sale = pd.DataFrame(data = {'MANAGER':['Anna', 'Anna', 'Martin', 'Anna', 'Martin', 'Martin', 'Anna', 'Martin'],
                               'CLIENTS':[2, 7, 5, 5, 4, 5, 8, 5],
                               'AMOUNT':[80.1, 10.2, 10., 80.3, 70., 100.2, 30., 40.5],
                               'SALESPERSON':['Ben', 'Andrew',  'Elisa', 'Kat', 'Tom', 'Bet', 'Elenore', 'Steve'],
                               'ACTIVE':['Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N']},
                       index = pd.DatetimeIndex(['2020-03-01', '2020-05-01', '2020-03-01', '2020-04-01', 
                                                 '2020-04-01', '2020-05-01', '2020-06-01', '2020-06-01']))

# Write your code here


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 18:</b>
<p>A DataFrame has been defined in the cell below. </p>

```python
df_sale = pd.DataFrame(data = {'MANAGER':['Anna', 'Anna', 'Martin', 'Anna', 'Martin', 'Martin', 
                                          'Anna', 'Martin'],
                               'CLIENTS':[2, 7, 5, 5, 4, 5, 8, 5],
                               'AMOUNT':[80.1, 10.2, 10., 80.3, 70., 100.2, 30., 40.5],
                               'SALESPERSON':['Ben', 'Andrew',  'Elisa', 'Kat', 'Tom', 'Bet', 
                                              'Elenore', 'Steve'],
                               'ACTIVE':['Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N']},
                       index = pd.DatetimeIndex(['2020-03-01', '2020-05-01', '2020-03-01', '2020-04-01', 
                                                 '2020-04-01', '2020-05-01', '2020-06-01', '2020-06-01']))
```
    
<p>Covert the column names from upper cases to lower cases. Display <code>df_sale</code>, the expected output is shown below.</p>
    
<img src="./Quiz8_files_1/Question18.png" width="40%">
    
<br>    
<p>Please <b>DON'T</b> rename the columns with a list of lower cased column names, e.g. <code>df_sale.columns = ['manager', 'clients', 'amount', 'salesperson', 'active']</code> or rename the column names one by one. </p>

</div>

In [ ]:
###ANSWER(18)
df_sale = pd.DataFrame(data = {'MANAGER':['Anna', 'Anna', 'Martin', 'Anna', 'Martin', 'Martin', 'Anna', 'Martin'],
                               'CLIENTS':[2, 7, 5, 5, 4, 5, 8, 5],
                               'AMOUNT':[80.1, 10.2, 10., 80.3, 70., 100.2, 30., 40.5],
                               'SALESPERSON':['Ben', 'Andrew',  'Elisa', 'Kat', 'Tom', 'Bet', 'Elenore', 'Steve'],
                               'ACTIVE':['Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N']},
                       index = pd.DatetimeIndex(['2020-03-01', '2020-05-01', '2020-03-01', '2020-04-01', 
                                                 '2020-04-01', '2020-05-01', '2020-06-01', '2020-06-01']))

# Write your code here


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 19:</b>
<p>A DataFrame has been defined in the cell below. </p>

```python
df_sale = pd.DataFrame(data = {'MANAGER':['Anna', 'Anna', 'Martin', 'Anna', 'Martin', 'Martin', 
                                          'Anna', 'Martin'],
                               'CLIENTS':[2, 7, 5, 5, 4, 5, 8, 5],
                               'AMOUNT':[80.1, 10.2, 10., 80.3, 70., 100.2, 30., 40.5],
                               'SALESPERSON':['Ben', 'Andrew',  'Elisa', 'Kat', 'Tom', 'Bet', 
                                              'Elenore', 'Steve'],
                               'ACTIVE':['Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N']},
                       index = pd.DatetimeIndex(['2020-03-01', '2020-05-01', '2020-03-01', '2020-04-01', 
                                                 '2020-04-01', '2020-05-01', '2020-06-01', '2020-06-01'])) 
```
    
<p>Replace the column <code>AMOUNT</code> with a new column called <code>AMOUNT_PERCENTAGE</code> which contains the percentage of amount (rounded to the <b>second</b> decimal) for each row. Please make sure the order of columns remains the same. Display <code>df_sale</code>, the expected output is shown below.</p>

<img src="./Quiz8_files_1/Question19.png" width="50%">

</div>

In [ ]:
###ANSWER(19)
df_sale = pd.DataFrame(data = {'MANAGER':['Anna', 'Anna', 'Martin', 'Anna', 'Martin', 'Martin', 'Anna', 'Martin'],
                               'CLIENTS':[2, 7, 5, 5, 4, 5, 8, 5],
                               'AMOUNT':[80.1, 10.2, 10., 80.3, 70., 100.2, 30., 40.5],
                               'SALESPERSON':['Ben', 'Andrew',  'Elisa', 'Kat', 'Tom', 'Bet', 'Elenore', 'Steve'],
                               'ACTIVE':['Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N']},
                       index = pd.DatetimeIndex(['2020-03-01', '2020-05-01', '2020-03-01', '2020-04-01', 
                                                 '2020-04-01', '2020-05-01', '2020-06-01', '2020-06-01']))

# Write your code here


In [ ]:
#Please leave this cell blank.

<div class="alert alert-warning">
<b>QUESTION 20:</b>
<p>A DataFrame <code>df_quiz</code> which contains the grades from Quiz_1 to Quiz_6 has been defined in the cell below. </p>

```python
df_quiz = pd.DataFrame(data = {'NAME':['Ben', 'Elisa', 'Kat', 'Tom', 'Diego', 'Xiaoming', 'Yun', 'Sofia'],
                               'Quiz_1': [90, 80, 70, 90, 40, 60, 77, 80],
                               'Quiz_2': [80, 64, 30, 80, 60, 42, 90, 43],
                               'Quiz_3': [64, 60, 68, 88, 70, 53, 88, 50],
                               'Quiz_4': [73, 93, 80, 94, 73, 60, 80, 87],
                               'Quiz_5': [68, 64, 55, 77, 61, 93, 54, 63],
                               'Quiz_6': [88, 74, 66, 74, 75, 60, 83, 77]})    
```
    
<p>When calculating the final grade, the 2 lowest grades will be dropped, and the average grade of the remaining 4 quizzes will be the final grade. Assign the result to a new column called <code>FINAL_GRADE</code> and calculate the final grade (rounded to the <b>first</b> decimal) for each student. Display <code>df_quiz</code>, the expected output is shown below.</p>

<img src="./Quiz8_files_1/Question20.png" width="50%">

</div>

In [ ]:
###ANSWER(20)
df_quiz = pd.DataFrame(data = {'NAME':['Ben', 'Elisa', 'Kat', 'Tom', 'Diego', 'Xiaoming', 'Yun', 'Sofia'],
                               'Quiz_1': [90, 80, 70, 90, 40, 60, 77, 80],
                               'Quiz_2': [80, 64, 30, 80, 60, 42, 90, 43],
                               'Quiz_3': [64, 60, 68, 88, 70, 53, 88, 50],
                               'Quiz_4': [73, 93, 80, 94, 73, 60, 80, 87],
                               'Quiz_5': [68, 64, 55, 77, 61, 93, 54, 63],
                               'Quiz_6': [88, 74, 66, 74, 75, 60, 83, 77]})

# Write your code here


In [ ]:
#Please leave this cell blank.